apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - generated-by-backstage
    - platform-engineering
    - devops
    - devsecops
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
