apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${{ values.name }}-allow-http
  labels:
    app: ${{ values.name }}
    owner: ${{ values.owner }}
    system: ${{ values.system }}
spec:
  podSelector:
    matchLabels:
      app: ${{ values.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: ${{ values.servicePort }}
