apiVersion: v1
kind: Service
metadata:
  name: ${{ values.serviceName }}
  labels:
    app.kubernetes.io/name: ${{ values.serviceName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: ${{ values.serviceName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
