{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${{ values.serviceName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.serviceName }}
  endpoints:
    - port: http
      path: /metrics
{{- end }}
