apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    owner: ${{ values.owner }}
    system: ${{ values.system }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
