apiVersion: v1
kind: Service
metadata:
name: ${{ values.name }}
labels:
app: ${{ values.name }}
spec:
type: ClusterIP
selector:
app: ${{ values.name }}
ports:
- name: http
port: 80
targetPort: ${{ values.servicePort }}
