---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Default local Backstage users
spec:
  type: team
  profile:
    displayName: Guests
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nolet7
spec:
  profile:
    displayName: Lateef Salam
    email: nolet7@gmail.com
  memberOf: [guests]
