apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: postgres-secret
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ .Values.global.appName }}
    backstage.io/owner: {{ .Values.global.owner | quote }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DB_HOST: {{ .Values.postgres.name | quote }}
  DB_PORT: {{ .Values.api.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.api.env.DB_NAME | quote }}
  DB_USER: {{ .Values.api.env.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
