replicaCount: 2

image:
  repository: ghcr.io/nolet7/${{ values.serviceName }}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: ${{ values.port }}

containerPort: ${{ values.port }}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

serviceMonitor:
  enabled: false
